### ISSUE TITLE
How to change header width?

### ISSUE THREAD

**Issue by sherlii** [sjaakvandenberg/flexy#1]
e.g. I can't find the setting of the header's width.

**Comment by sjaakvandenberg** [comment]
The width of the header relative to the main section on non-mobile screens is set using the `flex` shorthand on line 834 and 854 of [screen.styl](https://github.com/sjaakvandenberg/flexy/blob/master/source/styles/screen.styl).

For examples on how to use `flex`, see:

https://umaar.github.io/css-flexbox-demo/
http://tympanus.net/codrops/css_reference/flexbox/#section_flex

**Comment by sherlii** [comment]
it works. Thanks.
