### ISSUE TITLE
How do I add small buttons for social links when I use this theme

### ISSUE THREAD

**Issue by whitealco** [sjaakvandenberg/flexy#14]
How do I add small buttons for social links when I use this theme

**Comment by sjaakvandenberg** [comment]
Hi @whitealco , to add them to the sidebar, you can add them to _header.jade. To add them to the footer, to _footer.jade (both in the layout folder). You can stylize these in the stylus files in the source/styles folder).

**Comment by whitealco** [comment]
Thank you so much. 
This question has puzzled a newcomer for too long😂😂😂
