### ISSUE TITLE
blank page

### ISSUE THREAD

**Issue by drduan** [sjaakvandenberg/flexy#3]
I command that command and the corectly deploy it .and no error message but blank page

**Comment by sjaakvandenberg** [comment]
Which command?

**Comment by drduan** [comment]
ok, and now I try  using  another theme,but the page become this [blog site](http://hexo.superduan.xyz/)

**Comment by drduan** [comment]
<img width="636" alt="2016-01-27 17 09 26" src="https://cloud.githubusercontent.com/assets/7875572/12608738/c80f37ea-c518-11e5-9b8d-19e066f235bf.png">

**Comment by sjaakvandenberg** [comment]
This theme uses Jade, not EJS. Those are EJS tags.

**Comment by drduan** [comment]
thank you ~ 

```
$ npm un -S hexo-renderer-jade
$ npm i -S hexo-renderer-ejs
```

**Comment by sjaakvandenberg** [comment]
No problem :)
