### ISSUE TITLE
Hi)) 

### ISSUE THREAD

**Issue by makeroff** [sjaakvandenberg/flexy#4]
Beautiful theme! How to install wordpress. I write error stylesheet not found ((

**Comment by sjaakvandenberg** [comment]
This is a theme for [Hexo](https://hexo.io), not WordPress.

**Comment by makeroff** [comment]
hexo  suitable for Windows ? ))

**Comment by sjaakvandenberg** [comment]
> hexo suitable for Windows ? ))

Hexo runs on [NodeJS](https://nodejs.org/en/), which you can run on Windows. It will generate a static set of pages, which you could then host on a server (shared hosting, VPS, etc).

**Comment by makeroff** [comment]
Thanks for the help!

**Comment by sjaakvandenberg** [comment]
No problem, thanks for checking out the theme! :)
