### ISSUE TITLE
Jade renamed to pug

### ISSUE THREAD

**Issue by dreavega** [sjaakvandenberg/flexy#5]
when I try  "npm i -S hexo-renderer-jade" the command line tells me to replace jade with pug, but that command isnt recognized... Any suggestions? 
Really like this theme btw! Going to use it for my portfolio 👍

**Comment by sjaakvandenberg** [comment]
Ah, you're right, Jade has indeed been renamed to Pug. `hexo-renderer-pug` is available instead, but I haven't gotten around to upgrading and testing it. `hexo-renderer-jade` should still work in the meanwhile though.

Thanks for the compliment! Glad you like it :)

**Comment by dreavega** [comment]
Yea no worries, i figured it out! Might want to mention to install: "npm install pug" before cloning to avoid running into any problems. :)

**Comment by sjaakvandenberg** [comment]
Should this issue still be relevant, feel free to open a PR with a code improvement.
