### ISSUE TITLE
articles and about page can't open

### ISSUE THREAD

**Issue by wongsihan** [sjaakvandenberg/flexy#7]
i use command like"hexo new page "Articles"...and it works on localhost,but when I use my own domain name it doesn't work.the page of articles and about can not found.....my site is : sihan.me

**Comment by sjaakvandenberg** [comment]
You are using capitals in your page url. Check http://sihan.me/Articles/, that just works. You'd have to update the links in your sidebar to include capitals, if that's the desired behavior.

**Comment by wongsihan** [comment]
thank you  so~~~~ much, didn't notice capitals....your theme is pretty cool and I like it very much~

**Comment by sjaakvandenberg** [comment]
No problem, thanks for using it :)
