### ISSUE TITLE
The Problem Aboult layout

### ISSUE THREAD

**Issue by heyafei12138** [sjaakvandenberg/flexy#8]
i'd like to say that i like your 'flexy' very much ,but there is a question aboult layout whith i don't know how to do.  I think the description (on the left side of the black background)is too heavy,and i want to let it become thiner,it's width can littler.thanks.

**Comment by sjaakvandenberg** [comment]
You can just modify the settings in [screen.styl](https://github.com/sjaakvandenberg/flexy/blob/master/source/styles/screen.styl).
