### ISSUE TITLE
Tables look abnormal

### ISSUE THREAD

**Issue by DvDxx** [sjaakvandenberg/flexy#9]
the table seems it didn't work.
code in flexy theme
```
| Item     | Value        | Qty   |
| :------- | -----------: | :---: |
| Computer | 1600 USD     | 5     |
| Phone    | 12 USD       | 12    |
| Pipe     | 1 USD        | 234   |
```

the website show like the following picture:
![table error](https://user-images.githubusercontent.com/33486198/32607466-1b1d2f6e-c594-11e7-9925-68fc9b8797e1.png)

same code in default theme,it correctly show
![table correct](https://user-images.githubusercontent.com/33486198/32607443-0bc70184-c594-11e7-8068-bd91656cd247.png)

**Comment by sjaakvandenberg** [comment]
Should this issue still be relevant, feel free to open a PR with a code improvement.
